
<div class="row">
    
</div>
<div class="row">
    <div class="span8 offset2">
        <h1><strong>Remindavax is:</strong></h1>
        Remindavax provides a group of versatile, effective mHealth solutions
        which target treatment non-adherence. At Remindavax, we are driven to
        improve treatment adherence globally.
    </div>
</div>
<div class="row">
    <br />
    <div class="span8 offset2">
        <a id="button-signup" href="/signup">Sign Up</a>
        <div id="form-login">
        <?php echo $this->loginForm ?>
        </div>
    </div>
</div>


