<?php // header.phtml ?>
<header>
    <!-- id="main-header" class="cleared-container" -->
    
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
            <a class="brand" href="/">
              Reminda<span id="vax">vax</span>
            </a>
        </div>
      </div>
    </div>
    
    <!-- <h1>Reminda<span id="vax">vax</span>v2.0</h1> -->
    
    <!-- <a href=
    "<?php echo $this->url(
        array('controller'=>'profile','action'=>'settings'),
        'default',true) ?>"
        >Settings</a>
    <a href=
    "<?php echo $this->url(
        array('controller'=>'profile','action'=>'logout'),
        'default',true) ?>"
        >Logout</a>
    <a href=
    "<?php echo $this->url(
        array('controller'=>'patients','action'=>'index'),
        'default',true) ?>"
        >Patients</a> -->
        
</header>