<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Remindavax</title>
    
    <!--TWITTER BOOTSTRAP START-->
    <link rel="stylesheet/less" href="/ui/bootstrap/less/bootstrap.less">
    <script src="/ui/less.js"></script>
    <!--TWITTER BOOTSTRAP END-->
    
    <!--Personal CSS-->
    <!-- <link rel="stylesheet" type="text/css" href="<?php echo
        $this->baseUrl('ui/main.css'); ?>" />
    <link rel="stylesheet" type="text/css" href="<?php echo
        $this->baseUrl('ui/index.css'); ?>" /> -->
    <link rel="stylesheet" type="text/css" href="<?php echo
        $this->baseUrl('ui/main2.css'); ?>" />
    
    <?php echo $this->dojo();
          echo $this->dojo()->addStylesheetModule('dijit.themes.tundra'); ?>
</head>
