<script language="JavaScript">
function repeatsChange()
        {
            var value = document.getElementById('repeats').value;
            if (value != 1) {
                document.getElementById('repeatOn-element').style.display = 'none';
                document.getElementById('repeatOn-label').style.display = 'none';
            } else {
                document.getElementById('repeatOn-label').style.display = 'block';
                document.getElementById('repeatOn-element').style.display = 'block';
                
            }
        }
</script>
<!-- <style type="text/css">
    #repeatOn-element, #repeatOn-label {
        display:none;
    }
</style> -->
<!-- <body onload="Javascript: repeatsChange();"></body> -->
<div id="patientforms" class="cleared-container">
<?php
    foreach($this->patientForms as $form) {
        echo $form;
    }
?>
</div>